[package]
name = "voxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
egui = "0.29.1"
bytemuck = "^1.20.0"
winit = { version = "0.30.5", features = ["rwh_05"] }