[package]
name = "voxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
bytemuck = "1.18.0"
egui-ash = { version = "0.4.0", features = ["gpu-allocator"] }
gpu-allocator = "0.27.0"
