[package]
name = "voxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
egui = "0.30.0"
bytemuck = "1.21.0"
winit = { version = "0.30.7", features = ["rwh_05"] }