[package]
name = "voxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.1"
gpu-allocator = "0.27.0"
egui = "0.29.1"
egui_winit_vulkano = "0.27.0"
bytemuck = "1.19.0"
winit = "0.30.5"
